 author: “Trigger Ass admin@trigger-apps.com"
category: "http"
summary: "HTTP POST user's messages with extensions to target URL when user is offline for eJabberd 18.09"
home: "https://github.com/a-radwan/mod_offline_http_post_ext-master.git"
url: "https://github.com/a-radwan/mod_offline_http_post_ext-master.git"
